insert into bd values (1,'Les bijoux de la Castafiore','Hergé','Hergé','Casterman','Tintin', 21, 'aventure','BD','lesBijouxDeLaCastafiore.jpg');
insert into bd values (2,'Ame rouge','Juan Diaz Canales','Juanjo Guarnido','Dargaud','Blacksad', 3,'policier','BD', 'ameRouge.jpg');
insert into bd values (3,'Astérix le Gaulois','René Goscinny','Albert Uderzo','Hachette','Astérix', 1,'aventure','BD', 'asterixLeGaulois.jpg');
insert into bd values (4,'Persepolis - Tome 3','Marjane Satrapi','Marjane Satrapi',"L'association",'Persepolis', 3, 'autobiographie','BD', 'persepolis3.jpg');
insert into bd values (5,'Journal infime' , 'Julien Neel' , 'Julien Neel', 'Glénat', 'Lou !' , 1,  'jeunesse' , 'BD', 'journalInfime.jpeg');
insert into bd values (6,'Mortebouse' , 'Julien Neel' , 'Julien Neel', 'Glénat', 'Lou !' , 2,  'jeunesse' , 'BD', 'mortebouse.jpg');
insert into bd values (7,'Le cimetière des autobus' , 'Julien Neel' , 'Julien Neel', 'Glénat', 'Lou !', 3, 'jeunesse' , 'BD', 'leCimetiereDesAutobus.jpg');
insert into bd values (8,'Les Schtroumpfs olympiques' , 'Peyo' , 'Peyo', 'Dupuis', 'Les Schtroumpfs' , 11, 'jeunesse', 'BD', 'lesSchtroumpfsOlympiques.jpg');
insert into bd values (9,'La Soupe aux Schtroumpfs' ,'Peyo' , 'Peyo', 'Dupuis', 'Les Schtroumpfs' , 10, 'jeunesse' , 'BD', 'laSoupeAuxSchtroumpfs.jpg');
insert into bd values (10,'Le Cosmoschtroumpf' ,'Peyo' , 'Peyo', 'Dupuis', 'Les Schtroumpfs' , 6, 'jeunesse' , 'BD', 'leCosmoschtroumpf.jpg');
insert into bd values (11,'Faux départ !' ,'Cauvin' , 'Laudec', 'Dupuis', 'Cédric' , 28, 'humour' , 'BD', 'fauxDepart.jpg');
insert into bd values (12,'Graine de star' ,'Cauvin' , 'Laudec', 'Dupuis', 'Cédric' , 26, 'humour' , 'BD', 'graineDeStar.jpg');
insert into bd values (13,'La nuit de Saint-Germain-des-Prés','Léo Malet','Emmanuel Moynot','Casterman','Nestor Burma', 5, 'policier', 'BD','laNuitDeSaintGermainDesPres.jpg');
insert into bd values (14,'Revers de fortune','Alain Ayroles','Jean-Luc Masbou','Delcourt','De cape et de crocs', 9,'aventure', 'BD','reversDeFortune.jpg');
insert into bd values (15,'Maus','Art Spiegelman','Art Spiegelman','Flammarion',null, null, 'historique', 'BD','maus.jpg');
insert into bd values (16,"La pourpre et l'or",'Jean Dufaux','Philippe Delaby','Dargaud','Murena', 1, 'historique', 'BD','laPourpreEtLOr.jpg');
insert into bd values (17,'Quartier lointain','Jirô Taniguchi','Jirô Taniguchi','Casterman', null, null, 'vie', 'BD','quartierLointain.jpg');
insert into bd values (18, 'Naruto - Tome 9', 'Masashi Kishimoto','Masashi Kishimoto','Kana Eds','Naruto', 9, 'shonen', 'Manga', 'naruto9.jpg');
insert into bd values (19, 'Naruto - Tome 6', 'Masashi Kishimoto','Masashi Kishimoto','Kana Eds','Naruto', 6, 'shonen', 'Manga', 'naruto6.jpg');
insert into bd values (20, 'À la rencontre de maître Chavipère', 'Eiichiro Oda', 'Eiichiro Oda', 'Glénat', 'One Piece', 81, 'shonen', 'Manga', 'onePiece81.jpeg');
insert into bd values (21, 'Déclaration de guerre', 'Eiichiro Oda', 'Eiichiro Oda', 'Glénat', 'One Piece', 41, 'shonen', 'Manga', 'onePiece41.jpg');
insert into bd values (22, 'La saga du Phénix Noir', 'Chris Claremont', 'John Byrne', 'Panini Comics', 'X-Men', null, 'science fiction', 'Comic', 'laSagaDuPhenixNoir.jpg');

insert into personne values (1,'fanDeBd','bonjour','utilisateur');
insert into personne values (2,'admin1','gestion','administrateur');
insert into personne values (3,'roger','vivelabd','utilisateur');

insert into relation values(1,1,1,'possede');
insert into relation values(2,1,2,'veut');
insert into relation values(3,3,1,'possede');
insert into relation values(4,3,4,'possede');
insert into relation values(5,3,3,'veut');
insert into relation values(6,1,10,'possede');
insert into relation values(7,1,14,'possede');
insert into relation values(8,1,18,'veut');
insert into relation values(9,1,15,'veut');
insert into relation values(10,3,8,'possede');
insert into relation values(11,3,22,'veut');
insert into relation values(12,3,5,'veut');
insert into relation values(13,1,21,'possede');
insert into relation values(14,1,13,'possede');